# 创建一个 Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-net-test
---
# 创建一个 Pod
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: k8s-net-test
  labels:
    app: my-app
spec:
  containers:
    - name: my-container
      image: nginx:latest
      ports:
        - containerPort: 80
---
# 创建一个 Service
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: k8s-net-test
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP