# 创建一个 Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-net-test
---
#创建一个NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-external-service
  namespace: k8s-net-test
spec:
  selector:
    app: mysql-app
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ExternalName
  externalName: 192.168.0.230