# 创建一个 Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-net-test
---
# 创建一个 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: k8s-net-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
#创建一个NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: k8s-net-test
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort